Increase network packet size to 256
t-oster/LibLaserCut pull request #188
Opened 2023-02-08 18:50 UTC by kkaempf

Was 16 before with a noticable checksum overhead.

Signed-off-by: Klaus Kämpf <kkaempf@gmail.com>

2023-02-08 18:50 UTC, kkaempf commented
This one's for @jnweiger

2023-02-18 12:15 UTC, mgmax commented
Is this tested and ready to merge?

2023-02-23 01:45 UTC, jnweiger commented
Tested today: with 14cm x 14cm engrave at 500 dpi.
BUFLEN=16; -> ca 20 Minutes
BUFLEN=256; -> 2min 35 sec
BUFLEN=1024; -> 85 sec
BUFLEN=2048; -> 68 sec
BUFEN=4096; -> 60 sec
BUFLEN=8192; -> 59 sec

-> I suggest a larger bufsize than 256.

2023-02-23 01:47 UTC, jnweiger requested changes
BUFLEN=4096 is almost 3 times faster than BUFLEN=256;

2023-02-23 01:47 UTC, jnweiger commented on src/main/java/de/thomas_oster/liblasercut/drivers/Ruida.java
> +  public static final int BUFLEN = 256;
```suggestion
  public static final int BUFLEN = 4096;
```

2023-02-23 11:40 UTC, jnweiger approved these changes
Thanks!

2023-02-23 18:48 UTC, merged